/**
 * ═══════════════════════════════════════════════════════════
 *  ملف البيانات — تم إنشاؤه من لوحة التحكم Admin Panel
 *  Restaurant: موقع اختباري
 * ═══════════════════════════════════════════════════════════
 */

const MENU_DATA = {
  restaurant: {
    name: "موقع اختباري",
    nameEn: "test",
    welcome: "########",
    tagline: "############",
    phones: ["1111111111111", "222222222222", "333333333333"],
    address: "مول سايلو",
    deliveryNote: "أسرع دليفرى في مصر",
  },
  categories: [
    {
      id: "crepe-savory",
      name: "Crepe (Savory)",
      nameAr: "كريب حادق",
      items: [
        { id: "cs-1", name: "سجق", nameEn: "Sausage", description: "موتزاريلا وخضار", price: 110, image: "assets/images/migrated-cs-1.jpg" },
        { id: "cs-2", name: "برجر لحمة", nameEn: "Beef Burger", description: "موتزاريلا وخضار", price: 120, image: "assets/images/migrated-cs-2.jpg" },
        { id: "cs-3", name: "سوسيس", nameEn: "Hot Dog", description: "موتزاريلا وخضار", price: 150, image: "assets/images/migrated-cs-3.jpg" },
        { id: "cs-4", name: "فراخ باربيكيو", nameEn: "BBQ Chicken", description: "فراخ، مشروم، صوص باربيكيو", price: 110, image: "assets/images/migrated-cs-4.jpg" },
        { id: "cs-5", name: "فاهيتا فراخ", nameEn: "Chicken Fajita", description: "موتزاريلا وخضار", price: 100, image: "assets/images/migrated-cs-5.jpg" },
        { id: "cs-6", name: "مشكل لحوم", nameEn: "Meat Mix", description: "مفروم، سجق، بسطرمة", price: 110, image: "assets/images/migrated-cs-6.jpg" },
        { id: "cs-7", name: "مشكل جبن", nameEn: "Cheese Mix", description: "موتزاريلا، رومي، شيدر، كيري", price: 100, image: "assets/images/migrated-cs-7.jpg" },
        { id: "cs-8", name: "بانية", nameEn: "Pane", description: "موتزاريلا وخضار", price: 110, image: "assets/images/migrated-cs-8.jpg" },
        { id: "cs-9", name: "كريسبي أطياب", nameEn: "Atyab Crispy", description: "موتزاريلا وخضار", price: 85, image: "assets/images/migrated-cs-9.jpg" },
        { id: "cs-10", name: "بطاطس", nameEn: "Fries", description: "", price: 55, image: "assets/images/migrated-cs-10.jpg" },
        { id: "cs-11", name: "بطاطس كريسبي", nameEn: "Crispy Fries", description: "", price: 70, image: "assets/images/migrated-cs-11.jpg" },
        { id: "cs-12", name: "مكس فراخ", nameEn: "Chicken Mix", description: "فراخ متبلة، كريسبي، بانية", price: 110, image: "assets/images/migrated-cs-12.jpg" },
        { id: "cs-13", name: "سوبر كرانشي", nameEn: "Super Crunchy", description: "كريسبي، سجق، شيدر", price: 110, image: "assets/images/migrated-cs-13.jpg" },
        { id: "cs-14", name: "قنبلة", nameEn: "The Bomb", description: "مشكل لحوم، مشكل جبن، كريسبي", price: 120, image: "assets/images/migrated-cs-14.jpg" },
        { id: "cs-15", name: "استربس", nameEn: "Strips", description: "موتزاريلا وخضار", price: 110, image: "assets/images/migrated-cs-15.jpg" },
        { id: "cs-16", name: "كريب الباتشينو", nameEn: "Al Pacino Crepe", description: "تركي، سلامي، كيري، رانش", price: 130, image: "assets/images/migrated-cs-16.jpg" },
        { id: "cs-17", name: "كريب بسطرمة", nameEn: "Pastrami Crepe", description: "موتزاريلا وخضار", price: 110, image: "assets/images/migrated-cs-17.jpg" },
        { id: "cs-18", name: "كريب لذة الملوك", nameEn: "Lazat Al-Molouk Crepe", description: "تركي، استربس، كريسبي، كيري، سجق، رومي، بطاطس، موتزاريلا", price: 180, image: "assets/images/migrated-cs-18.jpg" },
      ],
    },
    {
      id: "crepe-sweet",
      name: "Crepe (Sweet)",
      nameAr: "كريب حلو",
      items: [
        { id: "cw-1", name: "شيكولاته وموز وبندق", nameEn: "Chocolate Banana Hazelnut", description: "", price: 80, image: "assets/images/migrated-cw-1.webp" },
        { id: "cw-2", name: "بوريو", nameEn: "Oreo", description: "", price: 70, image: "assets/images/migrated-cw-2.webp" },
        { id: "cw-3", name: "هوهوز", nameEn: "Hohos", description: "", price: 70, image: "assets/images/migrated-cw-3.webp" },
      ],
    },
    {
      id: "pizza",
      name: "Pizza",
      nameAr: "البيتزا",
      note: "يوجد بيتزا حشو أطراف — سوسيس أو موتزاريلا",
      items: [
        { id: "pz-1", name: "مارجريتا", nameEn: "Margherita", description: "موتزاريلا، صوص، خضار", prices: { L: 200, M: 140, S: 90 }, image: "assets/images/migrated-pz-1.webp" },
        { id: "pz-2", name: "تشيكن باربيكيو", nameEn: "Chicken BBQ", description: "فراخ، مشروم، موتزاريلا، صوص باربيكيو", prices: { L: 240, M: 180, S: 110 }, image: "assets/images/migrated-pz-2.webp" },
        { id: "pz-3", name: "كريزي تشيكن", nameEn: "Crazy Chicken", description: "فراخ، مشروم، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 100 }, image: "assets/images/migrated-pz-3.webp" },
        { id: "pz-4", name: "تونة", nameEn: "Tuna", description: "تونة، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-4.webp" },
        { id: "pz-5", name: "جمبري", nameEn: "Shrimp", description: "جمبري، موتزاريلا، خضار", prices: { L: 260, M: 200, S: 150 }, image: "assets/images/migrated-pz-5.webp" },
        { id: "pz-6", name: "فواكه البحر", nameEn: "Seafood", description: "جمبري، كالاماري، تونة، خضار", prices: { L: 270, M: 220, S: 160 }, image: "assets/images/migrated-pz-6.webp" },
        { id: "pz-7", name: "تريبيانا BBQ", nameEn: "Tribiana BBQ", description: "سجق، مشروم، موتزاريلا، صوص بارد", prices: { L: 230, M: 150, S: 110 }, image: "assets/images/migrated-pz-7.webp" },
        { id: "pz-8", name: "فراخ رانش", nameEn: "Chicken Ranch", description: "فراخ، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 115 }, image: "assets/images/migrated-pz-8.webp" },
        { id: "pz-9", name: "كواترو فور ماجيو", nameEn: "Quattro Formaggi", description: "صوص، خضار، 4 أنواع جبن", prices: { L: 230, M: 150, S: 100 }, image: "assets/images/migrated-pz-9.webp" },
        { id: "pz-10", name: "فور تشيز", nameEn: "Four Cheese", description: "كيري، موتزاريلا، شيدر، رومي، زيتون", prices: { L: 230, M: 150, S: 100 }, image: "assets/images/migrated-pz-10.webp" },
        { id: "pz-11", name: "فونجي", nameEn: "Funghi", description: "مشروم، موتزاريلا، خضار", prices: { L: 230, M: 160, S: 100 }, image: "assets/images/migrated-pz-11.webp" },
        { id: "pz-12", name: "بيبروني", nameEn: "Pepperoni", description: "بيبروني، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-12.webp" },
        { id: "pz-13", name: "سلامي", nameEn: "Salami", description: "سلامي، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-13.webp" },
        { id: "pz-14", name: "سجق", nameEn: "Sojouk", description: "سجق، موتزاريلا، خضار", prices: { L: 230, M: 160, S: 100 }, image: "assets/images/migrated-pz-14.webp" },
        { id: "pz-15", name: "بلونيز", nameEn: "Bolognese", description: "مفروم، موتزاريلا، خضار", prices: { L: 230, M: 160, S: 100 }, image: "assets/images/migrated-pz-15.webp" },
        { id: "pz-16", name: "فينسيا", nameEn: "Venice", description: "بسطرمة، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 105 }, image: "assets/images/migrated-pz-16.webp" },
        { id: "pz-17", name: "ميكس لحوم", nameEn: "Meat Mix", description: "مفروم، سجق، بسطرمة، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-17.webp" },
        { id: "pz-18", name: "سوبر سوبريم", nameEn: "Super Supreme", description: "بسطرمة، سلامي، مشروم، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-18.webp" },
        { id: "pz-19", name: "سوبر بيف", nameEn: "Super Beef", description: "مفروم، سوسيس، سلامي، موتزاريلا، خضار", prices: { L: 220, M: 160, S: 110 }, image: "assets/images/migrated-pz-19.webp" },
        { id: "pz-20", name: "شيكاغو", nameEn: "Chicago", description: "مفروم، سوسيس، موتزاريلا، خضار", prices: { L: 230, M: 160, S: 100 }, image: "assets/images/migrated-pz-20.webp" },
        { id: "pz-21", name: "سوسيس", nameEn: "Hot Dog", description: "سوسيس، موتزاريلا، خضار", prices: { L: 220, M: 160, S: 100 }, image: "assets/images/migrated-pz-21.webp" },
        { id: "pz-22", name: "لذة الملوك", nameEn: "Kings Delight", description: "مشكل جبن، مشكل لحوم، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-22.webp" },
        { id: "pz-23", name: "الباتشينو", nameEn: "Al Pacino", description: "تركي، كيري، فراخ، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-pz-23.webp" },
        { id: "pz-24", name: "حلواني", nameEn: "Halawani", description: "تركي، سلامي، موتزاريلا، خضار", prices: { L: 240, M: 180, S: 100 }, image: "assets/images/migrated-pz-24.webp" },
        { id: "pz-25", name: "سموك ترك", nameEn: "Smoked Turkey", description: "تركي مدخن، موتزاريلا، خضار", prices: { L: 230, M: 160, S: 100 }, image: "assets/images/migrated-pz-25.webp" },
        { id: "pz-26", name: "بيتزا فراخ", nameEn: "Chicken Pizza", description: "فراخ، موتزاريلا، خضار", prices: { L: 230, M: 170, S: 100 }, image: "assets/images/migrated-pz-26.webp" },
        { id: "pz-27", name: "حشو أطراف", nameEn: "Stuffed Crust", description: "سوسيس أو موتزاريلا", prices: { L: 100, M: 80, S: 55 }, image: "assets/images/migrated-pz-27.webp" },
      ],
    },
    {
      id: "savory-feteer",
      name: "Savory Feteer",
      nameAr: "الفطير الحادق",
      items: [
        { id: "sf-1", name: "جبنة رومي", nameEn: "Roumi Cheese", description: "رومي، خضار، موتزاريلا", prices: { L: 210, M: 170, S: 110 }, image: "assets/images/migrated-sf-1.webp" },
        { id: "sf-2", name: "جبنة موتزاريلا", nameEn: "Mozzarella", description: "موتزاريلا، خضار، رومي", prices: { L: 210, M: 170, S: 110 }, image: "assets/images/migrated-sf-2.webp" },
        { id: "sf-3", name: "جبنة كيري", nameEn: "Kiri Cheese", description: "كيري، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-sf-3.webp" },
        { id: "sf-4", name: "مشكل جبن", nameEn: "Mixed Cheese", description: "كيري، شيدر، رومي، خضار، موتزاريلا", prices: { L: 240, M: 180, S: 120 }, image: "assets/images/migrated-sf-4.webp" },
        { id: "sf-5", name: "سوسيس", nameEn: "Hot Dog", description: "سوسيس، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-sf-5.webp" },
        { id: "sf-6", name: "مفروم", nameEn: "Minced Meat", description: "مفروم، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-sf-6.webp" },
        { id: "sf-7", name: "سجق بلدي", nameEn: "Baladi Sausage", description: "سجق، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-sf-7.webp" },
        { id: "sf-8", name: "بسطرمة", nameEn: "Pastrami", description: "بسطرمة، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 120 }, image: "assets/images/migrated-sf-8.webp" },
        { id: "sf-9", name: "مشكل لحوم", nameEn: "Mixed Meat", description: "مفروم، سجق، بسطرمة، خضار", prices: { L: 240, M: 170, S: 120 }, image: "assets/images/migrated-sf-9.webp" },
        { id: "sf-10", name: "سلامي", nameEn: "Salami", description: "سلامي، خضار، موتزاريلا", prices: { L: 230, M: 170, S: 110 }, image: "assets/images/migrated-sf-10.webp" },
        { id: "sf-11", name: "سجق والجبنة الكيري", nameEn: "Sojouk and Kiri", description: "سجق، كيري، رومي، خضار، موتزاريلا", prices: { L: 240, M: 180, S: 120 }, image: "assets/images/migrated-sf-11.webp" },
        { id: "sf-12", name: "الباتشينو", nameEn: "Al Pacino", description: "تركي، كيري، فراخ، خضار، موتزاريلا", prices: { L: 240, M: 180, S: 120 }, image: "assets/images/migrated-sf-12.webp" },
        { id: "sf-13", name: "ديك رومي", nameEn: "Turkey", description: "تركي، خضار، موتزاريلا", prices: { L: 240, M: 170, S: 110 }, image: "assets/images/migrated-sf-13.webp" },
        { id: "sf-14", name: "دجاج", nameEn: "Chicken", description: "فراخ متبلة، خضار، موتزاريلا", prices: { L: 240, M: 170, S: 120 }, image: "assets/images/migrated-sf-14.webp" },
        { id: "sf-15", name: "ميكس فراخ", nameEn: "Chicken Mix", description: "ميكس فراخ، خضار، موتزاريلا", prices: { L: 240, M: 170, S: 120 }, image: "assets/images/migrated-sf-15.webp" },
        { id: "sf-16", name: "مشروم", nameEn: "Mushroom", description: "مشروم، خضار، موتزاريلا", prices: { L: 220, M: 160, S: 110 }, image: "assets/images/migrated-sf-16.webp" },
        { id: "sf-17", name: "تونة", nameEn: "Tuna", description: "تونة، خضار، موتزاريلا", prices: { L: 240, M: 170, S: 120 }, image: "assets/images/migrated-sf-17.webp" },
        { id: "sf-18", name: "جمبري", nameEn: "Shrimp", description: "جمبري، خضار، موتزاريلا", prices: { L: 260, M: 210, S: 150 }, image: "assets/images/migrated-sf-18.webp" },
        { id: "sf-19", name: "فواكه البحر", nameEn: "Seafood", description: "جمبري، كالاماري، تونة، خضار، موتزاريلا", prices: { L: 270, M: 220, S: 160 }, image: "assets/images/migrated-sf-19.webp" },
        { id: "sf-20", name: "لذة الملوك", nameEn: "Kings Delight", description: "سلامي، بسطرمة، روست بيف، تركي، كيري", prices: { L: 250, M: 180, S: 150 }, image: "assets/images/migrated-sf-20.webp" },
        { id: "sf-21", name: "قنبلة", nameEn: "The Bomb", description: "مفروم، سجق، بسطرمة، كيري، شيدر، رومي", prices: { L: 240, M: 180, S: 120 }, image: "assets/images/migrated-sf-21.webp" },
        { id: "sf-22", name: "بسطرمة كريانا", nameEn: "Pastrami Kiriana", description: "بسطرمة، كيري، شيدر، رومي، خضار، موتزاريلا", prices: { L: 240, M: 180 }, image: "assets/images/migrated-sf-22.webp" },
      ],
    },
    {
      id: "sweet-feteer",
      name: "Sweet Feteer",
      nameAr: "الفطير الحلو",
      items: [
        { id: "swf-1", name: "سكر", nameEn: "Sugar", description: "سكر، لبن، سمن", prices: { L: 120, M: 60 }, image: "assets/images/migrated-swf-1.webp" },
        { id: "swf-2", name: "كاستر", nameEn: "Custard", description: "كاسترد، سكر، لبن، سمن", prices: { L: 130, M: 70 }, image: "assets/images/migrated-swf-2.webp" },
        { id: "swf-3", name: "بغاشة بالقرفة", nameEn: "Cinnamon Baghasha", description: "قرفة، سكر، لبن، سمن", prices: { L: 130, M: 75 }, image: "assets/images/migrated-swf-3.webp" },
        { id: "swf-4", name: "قشطة", nameEn: "Cream", description: "قشطة، كاسترد، سكر، لبن، سمن", prices: { L: 150, M: 120 }, image: "assets/images/migrated-swf-4.webp" },
        { id: "swf-5", name: "ملوكي", nameEn: "Royal", description: "زبيب، جوز هند، كاسترد، سكر، لبن، سمن", prices: { L: 140, M: 95 }, image: "assets/images/migrated-swf-5.webp" },
        { id: "swf-6", name: "موز", nameEn: "Banana", description: "موز، كاسترد، سكر، لبن، سمن", prices: { L: 140, M: 100 }, image: "assets/images/migrated-swf-6.webp" },
        { id: "swf-7", name: "تفاح", nameEn: "Apple", description: "تفاح، كاسترد، سكر، لبن، سمن", prices: { L: 150, M: 110 }, image: "assets/images/migrated-swf-7.webp" },
        { id: "swf-8", name: "مربى وقشطة", nameEn: "Jam and Cream", description: "مربى، عسل، قشطة، كاسترد، سكر، لبن، سمن", prices: { L: 150, M: 120 }, image: "assets/images/migrated-swf-8.webp" },
        { id: "swf-9", name: "اسكندرية", nameEn: "Alexandria", description: "قشطة، عسل، كرز، كاسترد، سكر، لبن، سمن", prices: { L: 180, M: 140 }, image: "assets/images/migrated-swf-9.webp" },
        { id: "swf-10", name: "شيكولاته بالموز", nameEn: "Chocolate Banana", description: "شيكولاته، موز، بندق، كاسترد، سكر، لبن، سمن", prices: { L: 250, M: 180 }, image: "assets/images/migrated-swf-10.webp" },
        { id: "swf-11", name: "شيكولاته ميكس", nameEn: "Mixed Chocolate", description: "شيكولاته، شيكولاته بيضاء، كاسترد، سكر، لبن", prices: { L: 230, M: 165 }, image: "assets/images/migrated-swf-11.webp" },
        { id: "swf-12", name: "بلاك فورست", nameEn: "Black Forest", description: "نصف شيكولاته، نصف فواكه، مكسرات", prices: { L: 240, M: 170 }, image: "assets/images/migrated-swf-12.webp" },
        { id: "swf-13", name: "فروتي", nameEn: "Fruity", description: "فواكه مشكلة، قشطة، عسل، كرز", prices: { L: 180, M: 140 }, image: "assets/images/migrated-swf-13.webp" },
        { id: "swf-14", name: "بسبوسة أو كنافة", nameEn: "Basbousa or Kunafa", description: "بسبوسة أو كنافة، كاسترد، سكر، لبن، سمن", prices: { L: 180, M: 120 }, image: "assets/images/migrated-swf-14.webp" },
      ],
    },
    {
      id: "sawarekh",
      name: "Sawarekh",
      nameAr: "صاروخ",
      items: [
        { id: "sw-1", name: "صاروخ سجق", nameEn: "Sojouk Sarokh", description: "", prices: { L: 150, M: 110 }, image: "assets/images/sarokh-sojouk.jpg" },
        { id: "sw-2", name: "صاروخ لحمة", nameEn: "Meat Sarokh", description: "", prices: { L: 150, M: 110 }, image: "assets/images/sarokh-meat.jpg" },
        { id: "sw-3", name: "صاروخ سوسيس", nameEn: "Hot Dog Sarokh", description: "", prices: { L: 150, M: 110 }, image: "assets/images/sarokh-hotdog.jpg" },
        { id: "sw-4", name: "صاروخ سجق كيري", nameEn: "Sojouk Kiri Sarokh", description: "", prices: { L: 150, M: 120 }, image: "assets/images/sarokh-sojouk-kiri.jpg" },
        { id: "sw-5", name: "صاروخ فراخ", nameEn: "Chicken Sarokh", description: "", prices: { L: 160, M: 120 }, image: "assets/images/sarokh-chicken.jpg" },
        { id: "sw-6", name: "صاروخ بسطرمة كيري", nameEn: "Pastrami Kiri Sarokh", description: "", prices: { L: 160, M: 120 }, image: "assets/images/sarokh-pastrami-kiri.jpg" },
        { id: "sw-7", name: "صاروخ سوبر سوبريم", nameEn: "Super Supreme Sarokh", description: "", prices: { L: 160, M: 120 }, image: "assets/images/sarokh-supreme.jpg" },
        { id: "sw-8", name: "صاروخ لذة الملوك", nameEn: "Kings Delight Sarokh", description: "", prices: { L: 160, M: 120 }, image: "assets/images/sarokh-kings.jpg" },
      ],
    },
    {
      id: "sandwiches",
      name: "Sandwiches",
      nameAr: "الساندوتشات",
      items: [
        { id: "sn-1", name: "سجق", nameEn: "Sausage", description: "", prices: { L: 70, M: 45, S: 50 }, image: "assets/images/migrated-sn-1.webp" },
        { id: "sn-2", name: "فاهيتا فراخ", nameEn: "Chicken Fajita", description: "", prices: { L: 75, M: 55, S: 60 }, image: "assets/images/migrated-sn-2.webp" },
        { id: "sn-3", name: "فراخ بانية", nameEn: "Pane Chicken", description: "", prices: { L: 65, M: 40, S: 45 }, image: "assets/images/migrated-sn-3.webp" },
        { id: "sn-4", name: "ستربس", nameEn: "Strips", description: "", prices: { L: 75, M: 55, S: 60 }, image: "assets/images/migrated-sn-4.webp" },
        { id: "sn-5", name: "بطاطس", nameEn: "Fries", description: "", prices: { L: 50, M: 35, S: 40 }, image: "assets/images/migrated-sn-5.webp" },
        { id: "sn-6", name: "كبدة إسكندراني", nameEn: "Alexandrian Liver", description: "", prices: { L: 60, M: 40, S: 45 }, image: "assets/images/migrated-sn-6.webp" },
        { id: "sn-7", name: "كفتة", nameEn: "Kofta", description: "", prices: { L: 70, M: 50, S: 55 }, image: "assets/images/migrated-sn-7.webp" },
      ],
    },
    {
      id: "meals",
      name: "Meals",
      nameAr: "الوجبات",
      items: [
        { id: "ml-1", name: "وجبة فرخة مشوية", nameEn: "Grilled Chicken Meal", description: "", price: 400, image: "assets/images/migrated-ml-1.webp" },
        { id: "ml-2", name: "وجبة ربع فراخ", nameEn: "Quarter Chicken Meal", description: "", price: 110, image: "assets/images/migrated-ml-2.webp" },
        { id: "ml-3", name: "وجبة نص فراخ", nameEn: "Half Chicken Meal", description: "", price: 200, image: "assets/images/migrated-ml-3.webp" },
        { id: "ml-4", name: "وجبة ربع كفتة", nameEn: "Quarter Kofta Meal", description: "", price: 110, image: "assets/images/migrated-ml-4.webp" },
        { id: "ml-5", name: "وجبة نص كفتة", nameEn: "Half Kofta Meal", description: "", price: 200, image: "assets/images/migrated-ml-5.webp" },
        { id: "ml-6", name: "كيلو كفتة", nameEn: "Kilo Kofta", description: "", price: 400, image: "assets/images/migrated-ml-6.webp" },
        { id: "ml-7", name: "ساندوتش كفتة عيش بلدي", nameEn: "Kofta Baladi Sandwich", description: "", price: 30, image: "assets/images/meal-kofta-baladi.jpg" },
        { id: "ml-8", name: "ساندوتش كبدة عيش بلدي", nameEn: "Liver Baladi Sandwich", description: "", price: 30, image: "assets/images/meal-liver-baladi.jpg" },
      ],
    },
    {
      id: "pasta",
      name: "Pasta",
      nameAr: "الباستا",
      items: [
        { id: "pa-1", name: "اسباجيتي بالصوص والخضار", nameEn: "Spaghetti with Sauce", description: "", price: 75, image: "assets/images/migrated-pa-1.webp" },
        { id: "pa-2", name: "مكرونة فرن", nameEn: "Oven Pasta", description: "لحوم، صوص، موتزاريلا", price: 110, image: "assets/images/migrated-pa-2.webp" },
        { id: "pa-3", name: "باستا مشروم", nameEn: "Mushroom Pasta", description: "", price: 110, image: "assets/images/migrated-pa-3.webp" },
        { id: "pa-4", name: "اسباجيتي بلونيز", nameEn: "Spaghetti Bolognese", description: "", price: 110, image: "assets/images/migrated-pa-4.webp" },
        { id: "pa-5", name: "اسباجيتي إسكندراني", nameEn: "Alexandrian Spaghetti", description: "سجق، خضار، جبنة رومي", price: 110, image: "assets/images/migrated-pa-5.webp" },
        { id: "pa-6", name: "باستا سوسيس", nameEn: "Sausage Pasta", description: "", price: 110, image: "assets/images/migrated-pa-6.webp" },
        { id: "pa-7", name: "باستا سجق", nameEn: "Sojouk Pasta", description: "", price: 110, image: "assets/images/migrated-pa-7.webp" },
        { id: "pa-8", name: "باستا مشكل لحوم", nameEn: "Meat Mix Pasta", description: "", price: 125, image: "assets/images/migrated-pa-8.webp" },
        { id: "pa-9", name: "باستا مشكل جبن", nameEn: "Cheese Mix Pasta", description: "", price: 115, image: "assets/images/migrated-pa-9.webp" },
        { id: "pa-10", name: "نجرسكو فراخ", nameEn: "Chicken Negresco", description: "", price: 120, image: "assets/images/migrated-pa-10.webp" },
        { id: "pa-11", name: "باستا بصدور الديك الرومي", nameEn: "Turkey Breast Pasta", description: "", price: 125, image: "assets/images/migrated-pa-11.webp" },
        { id: "pa-12", name: "باستا ميكس فراخ", nameEn: "Chicken Mix Pasta", description: "", price: 130, image: "assets/images/migrated-pa-12.webp" },
        { id: "pa-13", name: "وايت شريمب", nameEn: "White Shrimp", description: "جمبري، بيني، صوص كريمة", price: 160, image: "assets/images/migrated-pa-13.webp" },
        { id: "pa-14", name: "اسباجيتي جمبري", nameEn: "Shrimp Spaghetti", description: "", price: 150, image: "assets/images/migrated-pa-14.webp" },
        { id: "pa-15", name: "اسباجيتي فواكه البحر", nameEn: "Seafood Spaghetti", description: "جمبري، كالاماري، خضار", price: 160, image: "assets/images/migrated-pa-15.webp" },
      ],
    },
    {
      id: "alexandrian-hawawshi",
      name: "Alexandrian Hawawshi",
      nameAr: "حواوشي إسكندراني",
      items: [
        { id: "hw-1", name: "حواوشي إسكندراني (لحمة أو سجق)", nameEn: "Meat or Sojouk", description: "", prices: { L: 75, M: 50 }, image: "assets/images/migrated-hw-1.webp" },
        { id: "hw-2", name: "حواوشي إسكندراني مخصوص", nameEn: "Special Hawawshi", description: "مع موتزاريلا", prices: { L: 80, M: 60 }, image: "assets/images/migrated-hw-2.webp" },
        { id: "hw-3", name: "حواوشي عيش بلدي", nameEn: "Baladi Bread Hawawshi", description: "", price: 30, image: "assets/images/migrated-hw-3.webp" },
      ],
    },
    {
      id: "calzone",
      name: "Calzone",
      nameAr: "كالزوني",
      items: [
        { id: "cz-1", name: "فراخ", nameEn: "Chicken", description: "", price: 100, image: "assets/images/migrated-cz-1.webp" },
        { id: "cz-2", name: "لحمة", nameEn: "Meat", description: "", price: 100, image: "assets/images/migrated-cz-2.webp" },
        { id: "cz-3", name: "سوسيس", nameEn: "Hot Dog", description: "", price: 100, image: "assets/images/migrated-cz-3.webp" },
        { id: "cz-4", name: "سجق", nameEn: "Sojouk", description: "", price: 100, image: "assets/images/migrated-cz-4.webp" },
        { id: "cz-5", name: "ميكس لحوم", nameEn: "Meat Mix", description: "", price: 110, image: "assets/images/migrated-cz-5.webp" },
      ],
    },
    {
      id: "additions",
      name: "Additions",
      nameAr: "الإضافات",
      items: [
        { id: "ad-1", name: "جبنة", nameEn: "Cheese", description: "", prices: { L: 40, M: 30, S: 20 }, image: "assets/images/add-cheese.jpg" },
        { id: "ad-2", name: "لحوم", nameEn: "Meats", description: "", prices: { L: 40, M: 30, S: 20 }, image: "assets/images/add-meats.jpg" },
        { id: "ad-3", name: "أسماك", nameEn: "Fish", description: "", price: 50, image: "assets/images/add-fish.jpg" },
        { id: "ad-4", name: "بطاطس", nameEn: "Fries", description: "", price: 10, image: "assets/images/add-fries.jpg" },
      ],
    },
    {
      id: "appetizers",
      name: "Appetizers",
      nameAr: "المقبلات",
      items: [
        { id: "ap-1", name: "كلوسلو", nameEn: "Coleslaw", description: "", price: 25, image: "assets/images/migrated-ap-1.webp" },
        { id: "ap-2", name: "سلطة خضراء", nameEn: "Green Salad", description: "", price: 10, image: "assets/images/migrated-ap-2.webp" },
        { id: "ap-3", name: "بوم فريت", nameEn: "Pomme Frites", description: "", prices: { L: 50, M: 30 }, image: "assets/images/app-fries.jpg" },
        { id: "ap-4", name: "عيش بالثوم", nameEn: "Garlic Bread", description: "", price: 25, image: "assets/images/app-garlic-bread.jpg" },
      ],
    },
    {
      id: "meshaltet",
      name: "Meshaltet",
      nameAr: "مشلتت",
      items: [
        { id: "ms-1", name: "مشلتت سادة", nameEn: "Plain Meshaltet", description: "", prices: { L: 200, M: 150 }, image: "assets/images/migrated-ms-1.webp" },
        { id: "ms-2", name: "مشلتت ست الحسن", nameEn: "Set El Hosn Meshaltet", description: "اسأل عن السعر", image: "assets/images/migrated-ms-2.webp" },
      ],
    }
  ],
};

const SOCIAL_LINKS = {
  whatsapp: "",
  facebook: "",
};

/**
 * عرض اليوم — يظهر كبانر أسفل الهيدر مباشرة في الصفحة الرئيسية.
 * عدّل active إلى false لإخفاء البانر تلقائياً.
 */
const DAILY_OFFER = {
  active: false,
  title: "خش توقع نتيجة مباراة منتخبنا على الفيس بتاعنا ونفذ الشروط عشان تكسب العرض معانا",
  item: "كريب على مزاجك",
  oldPrice: 0,
  newPrice: 0,
  note: "العرض هيتقفل قبل الماتش بنص ساعه",
};
